version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing docker"
      - ./install-docker.sh

  build:
    commands:
      - echo "Building Dockerfiles"
      - ./build-dockerfiles.sh