version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing docker"
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - chmod -R +x *
      - sudo sh get-docker.sh

  build:
    commands:
      - echo "Building Dockerfiles"
      - chmod -R +x *
      - ./build-dockerfiles.sh